version: '3'
services:
  web:
    build: .
    volumes:
      - ./../:/var/www/html/
    ports:
      - "127.0.0.1:80:80"
    stdin_open: true
    tty: true
  db:
    image: mariadb
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    ports:
      - "127.0.0.1:3306:3306"
  phpmyadmin:
    links:
      - db
    depends_on:
      - db
    image: adminer
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db
      MYSQL_ROOT_PASSWORD: dtb456
      PMA_HOST: db
      PMA_USER: db_user
      PMA_PASSWORD: dtb456